#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-2.0-only
#

# generated by tools/netifyd-update/netifyd-update.py, do not edit by hand

ifeq ($(ARCH),x86_64)
NETIFYD_FILE_NETIFYD:=netifyd
NETIFYD_HASH_NETIFYD:=6e7eab582e50318312fd63e3513beb8c11e5ccae86a92f071ba665f5ff14b009
NETIFYD_FILE_LIBNETIFYD:=libnetifyd.so.6.0.0
NETIFYD_SONAME_LIBNETIFYD:=libnetifyd.so.6
NETIFYD_LINK_LIBNETIFYD:=libnetifyd.so
NETIFYD_HASH_LIBNETIFYD:=c0241ccc9b80ed71af0456fba435b1f1dd77b6807297b0937ca021df1d6f4d32
NETIFYD_FILE_PLM:=libnetify-plm.so.1.0.0
NETIFYD_SONAME_PLM:=libnetify-plm.so.1
NETIFYD_LINK_PLM:=libnetify-plm.so
NETIFYD_HASH_PLM:=fdd7cc484a747125930e70a426ae714509888b34ab3f3dd3df70b421aff07a5e
NETIFYD_FILE_PROC_AGGREGATOR:=libnetify-proc-aggregator.so.0.0.0
NETIFYD_SONAME_PROC_AGGREGATOR:=libnetify-proc-aggregator.so.0
NETIFYD_LINK_PROC_AGGREGATOR:=libnetify-proc-aggregator.so
NETIFYD_HASH_PROC_AGGREGATOR:=49e19c6f827e70a50ad71f8d2cd55ddefeb08c7976184c69a4a7ec03e50b17cf
NETIFYD_FILE_PROC_CORE:=libnetify-proc-core.so.0.0.0
NETIFYD_SONAME_PROC_CORE:=libnetify-proc-core.so.0
NETIFYD_LINK_PROC_CORE:=libnetify-proc-core.so
NETIFYD_HASH_PROC_CORE:=7c3c661857e46ed4aed16da6f2f97999ab02a0b805c535cb0df6126899f2fa69
NETIFYD_FILE_PROC_FLOW_ACTIONS:=libnetify-proc-flow-actions.so.0.0.0
NETIFYD_SONAME_PROC_FLOW_ACTIONS:=libnetify-proc-flow-actions.so.0
NETIFYD_LINK_PROC_FLOW_ACTIONS:=libnetify-proc-flow-actions.so
NETIFYD_HASH_PROC_FLOW_ACTIONS:=69d36190737f8c739f8e7ee84810a833c38b0f0335db0094ca1cf2d54ad6dc00
NETIFYD_FILE_SINK_HTTP:=libnetify-sink-http.so.0.0.0
NETIFYD_SONAME_SINK_HTTP:=libnetify-sink-http.so.0
NETIFYD_LINK_SINK_HTTP:=libnetify-sink-http.so
NETIFYD_HASH_SINK_HTTP:=4b7f3f76d38c556c4fc1965a0458f8478eb7c872547248f46c5c5c0a143fccf0
NETIFYD_FILE_SINK_LOG:=libnetify-sink-log.so.0.0.0
NETIFYD_SONAME_SINK_LOG:=libnetify-sink-log.so.0
NETIFYD_LINK_SINK_LOG:=libnetify-sink-log.so
NETIFYD_HASH_SINK_LOG:=3ac13fd2b4b0ef035df529c5998a9d833e2a41372d20923885057f1e14e5a167
else ifeq ($(ARCH),aarch64)
NETIFYD_FILE_NETIFYD:=netifyd
NETIFYD_HASH_NETIFYD:=3cf1920be81a756b1bd8ff89855c35d00e9e069b6cf8d65c62f63a6e6f3ca27e
NETIFYD_FILE_LIBNETIFYD:=libnetifyd.so.15.0.0
NETIFYD_SONAME_LIBNETIFYD:=libnetifyd.so.15
NETIFYD_LINK_LIBNETIFYD:=libnetifyd.so
NETIFYD_HASH_LIBNETIFYD:=9ee8c3e3d0cded536c2759edf500ea0fff1dfddc79743b5a6bf79b439041d48c
NETIFYD_FILE_PLM:=libnetify-plm.so.1.0.0
NETIFYD_SONAME_PLM:=libnetify-plm.so.1
NETIFYD_LINK_PLM:=libnetify-plm.so
NETIFYD_HASH_PLM:=6e1cc96df0eb88bd4982f2716e21f894f309c5725024934be839ebc3fa9d5fc2
NETIFYD_FILE_PROC_AGGREGATOR:=libnetify-proc-aggregator.so.0.0.0
NETIFYD_SONAME_PROC_AGGREGATOR:=libnetify-proc-aggregator.so.0
NETIFYD_LINK_PROC_AGGREGATOR:=libnetify-proc-aggregator.so
NETIFYD_HASH_PROC_AGGREGATOR:=6c3e8612446bb7f73fff1abc969ab4f3abded6f1ffb5bd9bd41907ce154a0ee9
NETIFYD_FILE_PROC_CORE:=libnetify-proc-core.so.0.0.0
NETIFYD_SONAME_PROC_CORE:=libnetify-proc-core.so.0
NETIFYD_LINK_PROC_CORE:=libnetify-proc-core.so
NETIFYD_HASH_PROC_CORE:=30543afd01d30ddb3501e2d35b4c2ef8932649241d6d79052de70eafd9e7905a
NETIFYD_FILE_PROC_FLOW_ACTIONS:=libnetify-proc-flow-actions.so.0.0.0
NETIFYD_SONAME_PROC_FLOW_ACTIONS:=libnetify-proc-flow-actions.so.0
NETIFYD_LINK_PROC_FLOW_ACTIONS:=libnetify-proc-flow-actions.so
NETIFYD_HASH_PROC_FLOW_ACTIONS:=98331ecd54ee05c7155a4072ec7ceeaa9430a6231fe09ef67f8d4c03d446f9ac
NETIFYD_FILE_SINK_HTTP:=libnetify-sink-http.so.0.0.0
NETIFYD_SONAME_SINK_HTTP:=libnetify-sink-http.so.0
NETIFYD_LINK_SINK_HTTP:=libnetify-sink-http.so
NETIFYD_HASH_SINK_HTTP:=60b884abc641308c66207bf7de348b4b3f8c2d4b2d0091f3879dfa4f31a49fd8
NETIFYD_FILE_SINK_LOG:=libnetify-sink-log.so.0.0.0
NETIFYD_SONAME_SINK_LOG:=libnetify-sink-log.so.0
NETIFYD_LINK_SINK_LOG:=libnetify-sink-log.so
NETIFYD_HASH_SINK_LOG:=4dab9d43bda317f7c19269cd675ff8640417faeb82211a599abf8a1ddf2110e2
else
# metadata scan (DUMP=1, no .config) or an arch we ship no binaries for:
# placeholders only, netifyd is not selectable there and nothing is downloaded
NETIFYD_FILE_NETIFYD:=netifyd
NETIFYD_FILE_LIBNETIFYD:=libnetifyd.so
NETIFYD_SONAME_LIBNETIFYD:=libnetifyd.so
NETIFYD_LINK_LIBNETIFYD:=libnetifyd.so
NETIFYD_FILE_PLM:=libnetify-plm.so
NETIFYD_SONAME_PLM:=libnetify-plm.so
NETIFYD_LINK_PLM:=libnetify-plm.so
NETIFYD_FILE_PROC_AGGREGATOR:=libnetify-proc-aggregator.so
NETIFYD_SONAME_PROC_AGGREGATOR:=libnetify-proc-aggregator.so
NETIFYD_LINK_PROC_AGGREGATOR:=libnetify-proc-aggregator.so
NETIFYD_FILE_PROC_CORE:=libnetify-proc-core.so
NETIFYD_SONAME_PROC_CORE:=libnetify-proc-core.so
NETIFYD_LINK_PROC_CORE:=libnetify-proc-core.so
NETIFYD_FILE_PROC_FLOW_ACTIONS:=libnetify-proc-flow-actions.so
NETIFYD_SONAME_PROC_FLOW_ACTIONS:=libnetify-proc-flow-actions.so
NETIFYD_LINK_PROC_FLOW_ACTIONS:=libnetify-proc-flow-actions.so
NETIFYD_FILE_SINK_HTTP:=libnetify-sink-http.so
NETIFYD_SONAME_SINK_HTTP:=libnetify-sink-http.so
NETIFYD_LINK_SINK_HTTP:=libnetify-sink-http.so
NETIFYD_FILE_SINK_LOG:=libnetify-sink-log.so
NETIFYD_SONAME_SINK_LOG:=libnetify-sink-log.so
NETIFYD_LINK_SINK_LOG:=libnetify-sink-log.so
endif
