#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-2.0-only
#

#
# Launch podman image to build nethsecurity
# As default the script mounts as volume staging and build dirs to speedup successibe builds
#

workdir=$(pwd)
image_tag=${IMAGE_TAG:-latest}
image="ghcr.io/nethserver/nethsecurity-builder:$image_tag"

VALID_ARGS=$(getopt -o n --long no-cache -- "$@")
if [[ $? -ne 0 ]]; then
    exit 1;
fi

cache=1
opts=""

eval set -- "$VALID_ARGS"
while [ : ]; do
  case "$1" in
    -n | --no-cache)
        echo "Disable caching"
	cache=0
        shift
        ;;
    --) shift; 
        break 
        ;;
  esac
done

# Setup output dir
# Delete existing backup, but save current output before starting the build
if [ -d bin ]; then
    rm -rf bin.bak
    mv bin bin.bak
fi

# Setup cache volumes
if [ $cache -ge 1 ]; then
    opts=" -v nethsecurity-build_dir:/home/build/openwrt/build_dir:z -v nethsecurity-staging_dir:/home/build/openwrt/staging_dir:z -v nethsecurity-ccache:/home/build/openwrt/.ccache -v nethsecurity-download:/home/build/openwrt/download"
fi

# Download latest image
podman pull $image

# Renove existing container
if [ "$(podman ps -a --format '{{.Names}}')" == "nethsec-builder" ]; then
    podman rm nethsec-builder
fi

# Setup version from git
VERSION=$(git describe)
IS_STABLE=$(git describe --exact-match --tags HEAD 2>/dev/null)
if [ "$IS_STABLE" != "" ]; then
    CHANNEL="stable"
else
    CHANNEL="dev"
fi
export CHANNEL
export VERSION

# Setup CI when pushing to Github.
if [[ -n "${CI}" ]]; then
    # Set output value for Github Actions
    echo "version=$VERSION" >> "${GITHUB_ENV}"
    echo "::notice title=VERSION::{$VERSION}"
    echo "channel=$CHANNEL" >> "${GITHU_ENV}"
    echo "::notice title=CHANNEL::{$CHANNEL}"
fi

# Run podman with local mounted dirs
podman run -ti --name nethsec-builder \
    --security-opt label=disable \
    --env=USIGN_PUB_KEY --env=USIGN_PRIV_KEY \
    --env=NETIFYD_ACCESS_TOKEN \
    --env=VERSION --env=CHANNEL \
    -v ./config:/config:z -v ./files:/files:z -v ./packages:/nspackages:z -v ./patches:/patches:z \
    $opts $image "$@"
# When executed inside CI, do not execute next setps on error
ret=$?
if [[ $ret -gt 0 && -n "${CI}" ]]; then
    exit $ret
fi
podman cp nethsec-builder:/home/build/openwrt/bin/ $workdir/
if [ $? -eq 0 ]; then
    podman rm nethsec-builder
else
    echo
    echo "Export of built binaries failed: the container has not been removed"
    echo "To remove the container use: podman rm nethsec-builder"
    echo "To re-try export built binaries: podman cp nethsec-builder:/home/build/openwrt/bin/ $workdir/"
    echo
fi
