#!/bin/bash
#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-2.0-only
#

function load_kmap() {
    A=0;declare -a B
    for keymap in $(find /usr/share/keymaps/ -type f -name \*.bin); do
        echo "$(color_green ${A} )) ${keymap:19}"; ((A+=1));B+=($keymap);
    done; sleep 1;
    read -p "$(color_white 'Your choice: ')" keymap
    if [ ${keymap:-999} -ge 0 ] && [ ${keymap:-999} -lt $A ]; then
       loadkmap < ${B[$keymap]}
    else
       wrong_command;
    fi
}

function color_green(){
    echo -ne '\e[32m'$1'\e[0m'
}
function color_white(){
    echo -ne '\e[97m'$1'\e[0m'
}
function wrong_command(){
    echo -e '\e[31m'"Wrong option."'\e[0m';
}

function menu(){
   echo -ne "Quick options:\n"
   echo -ne "$(color_green '1)') Login\n"
   echo -ne "$(color_green '2)') Load alternate keyboard map (default is US)\n"
   echo -ne "$(color_white 'Choose an option:') "
   read choice
   case $choice in
	1) exec /bin/login ;;
	2) load_kmap; menu ;;
	*) wrong_command; menu ;;
        esac
}

# Call the menu function
/usr/bin/clear
/bin/cat /etc/banner
menu
