#!/bin/bash
#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-2.0-only
#

function print_help {
    echo "Usage: $0-f"
    echo "  -f: force factory reset, do not ask for confirmation"
    exit 1
}

function check {
    echo "All data will be lost!"
    read -rp "Do you want to proceed? (y/N) " force
    case $force in
        [yY] ) return 0;;
        * ) echo "Aborted"; exit 1;;
    esac
}

force=0
while getopts "hft::" opt; do
    case $opt in
        (f) force=1 ;; #Force write
        (h) print_help ;;
        (*) printf "Illegal option '-%s'\n" "$opt" && exit 1 ;;
    esac
done

if [ $force -le 0 ]; then
    check
fi
# download, install and reboot
img=$(/usr/bin/ns-download)
if [ -z "$img" ]; then
    echo "Aborted: image download failed"
    exit 1
else
    exec /sbin/sysupgrade -n -p "$img"
fi
