# Netify Device Discovery Processor Plugin Loader
#
##############################################################################

[proc-dev-discovery]
enable = no
plugin_library = ${path_plugin_libdir}/libnetify-proc-dev-discovery.so.0.0.0
conf_filename = ${path_state_persistent}/netify-proc-dev-discovery.json

# vim: set ft=dosini :
