#!/bin/sh

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-2.0-only
#

. /lib/functions/system.sh
. /lib/functions/uci-defaults.sh

board_config_update

case "$(board_name)" in
nethesis-nethbox-z11)
  ucidef_set_network_device_path "eth0" "pci0000:00/0000:00:01.0/0000:01:00.0" # fiber
  ucidef_set_network_device_path "eth1" "pci0000:00/0000:00:01.0/0000:01:00.1" # fiber
  ucidef_set_network_device_path "eth2" "pci0000:00/0000:00:1a.0/0000:03:00.0" # fiber
  ucidef_set_network_device_path "eth3" "pci0000:00/0000:00:1a.0/0000:03:00.1" # fiber
  ucidef_set_network_device_path "eth4" "pci0000:00/0000:00:1c.0/0000:04:00.0" # ethernet
  ucidef_set_network_device_path "eth5" "pci0000:00/0000:00:1c.1/0000:05:00.0" # ethernet
  ucidef_set_network_device_path "eth6" "pci0000:00/0000:00:1c.2/0000:06:00.0" # ethernet
  ucidef_set_network_device_path "eth7" "pci0000:00/0000:00:1c.3/0000:07:00.0" # ethernet
  ucidef_set_network_device_path "eth8" "pci0000:00/0000:00:1c.4/0000:08:00.0" # ethernet
  ucidef_set_network_device_path "eth9" "pci0000:00/0000:00:1c.5/0000:09:00.0" # ethernet
  ucidef_set_network_device_path "eth10" "pci0000:00/0000:00:1c.6/0000:0a:00.0" # ethernet
  ucidef_set_network_device_path "eth11" "pci0000:00/0000:00:1c.7/0000:0b:00.0" # ethernet
  ucidef_set_interface_lan "eth4"
  ;;
nethesis-nethbox-z7)
  # TODO: to be updated the PCie path
  ucidef_set_network_device_path "eth0" "pci0000:00/0000:00:01.0/0000:01:00.0"
  ucidef_set_network_device_path "eth1" "pci0000:00/0000:00:01.0/0000:01:00.1"
  ucidef_set_network_device_path "eth2" "pci0000:00/0000:00:1c.0/0000:03:00.0"
  ucidef_set_network_device_path "eth3" "pci0000:00/0000:00:1c.3/0000:04:00.0"
  ucidef_set_network_device_path "eth4" "pci0000:00/0000:00:1c.4/0000:05:00.0"
  ucidef_set_network_device_path "eth5" "pci0000:00/0000:00:1c.5/0000:06:00.0"
  ucidef_set_network_device_path "eth6" "pci0000:00/0000:00:1c.6/0000:07:00.0"
  ucidef_set_network_device_path "eth7" "pci0000:00/0000:00:1c.7/0000:08:00.0"
  ;;
nethesis-nethbox-z7s|default-string-default-string)
  # TODO: remove default-string-default-string
  ucidef_set_network_device_path "eth0" "pci0000:00/0000:00:01.0/0000:01:00.0" # fiber
  ucidef_set_network_device_path "eth1" "pci0000:00/0000:00:01.0/0000:01:00.1" # fiber
  ucidef_set_network_device_path "eth2" "pci0000:00/0000:00:1c.0/0000:03:00.0" # ethernet
  ucidef_set_network_device_path "eth3" "pci0000:00/0000:00:1c.3/0000:04:00.0" # ethernet
  ucidef_set_network_device_path "eth4" "pci0000:00/0000:00:1c.4/0000:05:00.0" # ethernet
  ucidef_set_network_device_path "eth5" "pci0000:00/0000:00:1c.5/0000:06:00.0" # ethernet
  ucidef_set_network_device_path "eth6" "pci0000:00/0000:00:1c.6/0000:07:00.0" # ethernet
  ucidef_set_network_device_path "eth7" "pci0000:00/0000:00:1c.7/0000:08:00.0" # ethernet
  ;;
nethesis-nethbox-z1)
  ucidef_set_network_device_path "eth0" "pci0000:00/0000:00:1c.0/0000:01:00.0" # ethernet
  ucidef_set_network_device_path "eth1" "pci0000:00/0000:00:1c.1/0000:02:00.0" # ethernet
  ucidef_set_network_device_path "eth2" "pci0000:00/0000:00:1c.2/0000:03:00.0" # ethernet
  ucidef_set_network_device_path "eth3" "pci0000:00/0000:00:1c.3/0000:04:00.0" # ethernet
  ucidef_set_interface_lan "eth0"
  ;;
esac
board_config_flush

exit 0

