# ns-stats configuration
#
##############################################################################

[proc-ns-stats]
enable = yes
plugin_library = ${path_plugin_libdir}/libnetify-proc-aggregator.so.0.0.0
conf_filename = ${path_state_persistent}/netify-ns-stats-proc.json

[sink-ns-stats]
enable = yes
plugin_library = ${path_plugin_libdir}/libnetify-sink-http.so.0.0.0
conf_filename = ${path_state_persistent}/netify-ns-stats-sink.json

# vim: set ft=dosini :
