# ns-flows configuration
#
##############################################################################

[proc-ns-flows]
enable = yes
plugin_library = ${path_plugin_libdir}/libnetify-proc-core.so.0.0.0
conf_filename = ${path_state_persistent}/netify-ns-flows-proc.json

[sink-ns-flows]
enable = yes
plugin_library = ${path_plugin_libdir}/libnetify-sink-http.so.0.0.0
conf_filename = ${path_state_persistent}/netify-ns-flows-sink.json

# vim: set ft=dosini :
