CONFIG_PACKAGE_ulogd=y
CONFIG_PACKAGE_ulogd-mod-dbi=y
CONFIG_PACKAGE_ulogd-mod-extra=y
CONFIG_PACKAGE_ulogd-mod-json=y
CONFIG_PACKAGE_ulogd-mod-mysql=y
CONFIG_PACKAGE_ulogd-mod-nfacct=y
CONFIG_PACKAGE_ulogd-mod-nfct=y
CONFIG_PACKAGE_ulogd-mod-nflog=y
CONFIG_PACKAGE_ulogd-mod-pcap=y
CONFIG_PACKAGE_ulogd-mod-pgsql=y
CONFIG_PACKAGE_ulogd-mod-sqlite=y
CONFIG_PACKAGE_ulogd-mod-syslog=y
CONFIG_PACKAGE_ulogd-mod-xml=y
