#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-2.0-only
#

# 2025-06-20
FROM debian:12.11
ARG SOURCE_DATE_EPOCH=1750425039
RUN apt-get update \
    && apt-get install --yes --no-install-recommends --no-install-suggests \
        bison \
        build-essential \
        ca-certificates \
        clang \
        curl \
        file \
        flex \
        g++ \
        gawk \
        gcc-multilib \
        gettext \
        git \
        libncurses5-dev \
        libssl-dev \
        python3-distutils \
        rsync \
        unzip \
        wget \
        zlib1g-dev \
    && useradd -m -s '/bin/bash' -U 'buildbot'

USER buildbot
WORKDIR /home/buildbot
# OpenWRT repo
ARG OWRT_VERSION
ENV OWRT_VERSION=${OWRT_VERSION}
RUN git clone --branch "v${OWRT_VERSION}" --depth 1 https://github.com/openwrt/openwrt.git
WORKDIR /home/buildbot/openwrt
RUN sed -i '/telephony/d' feeds.conf.default \
    && sed -i 's/src-git-full/src-git/' feeds.conf.default \
    && ./scripts/feeds update \
    && ./scripts/feeds install -a

# Nethsec packages and forks
COPY --chown=buildbot:buildbot packages nspackages
RUN echo "src-link nethsecurity /home/buildbot/openwrt/nspackages" >> feeds.conf.default \
    && ./scripts/feeds update nethsecurity \
    && ./scripts/feeds install -a -p nethsecurity
COPY --chmod=777 builder/package-replacement.sh /usr/local/bin/package-replacement
RUN package-replacement

# Patches to upstream packages
COPY --chown=buildbot:buildbot patches patches
COPY --chmod=777 builder/apply-patches.sh /usr/local/bin/apply-patches
RUN apply-patches

# Custom files in root
COPY --chown=buildbot:buildbot files files

# Build configuration
COPY --chown=buildbot:buildbot config config

# Build utils and volumes setup
COPY --chmod=777 builder/setup-build.sh /usr/local/bin/setup-build
COPY --chmod=777 builder/entrypoint.sh /usr/local/bin/entrypoint
ENTRYPOINT ["/usr/local/bin/entrypoint"]
CMD ["/bin/sh", "-c", "make -j$(nproc) world"]
RUN mkdir -p \
      .ccache \
      build_dir \
      dl \
      download \
      staging_dir
VOLUME "/home/buildbot/openwrt/.ccache", \
    "/home/buildbot/openwrt/build_dir", \
    "/home/buildbot/openwrt/dl", \
    "/home/buildbot/openwrt/download", \
    "/home/buildbot/openwrt/staging_dir"
