# banIP blocked-IP monitoring

[[inputs.tail]]
  name_override = "banip"
  files = ["/var/log/messages"]
  from_beginning = false
  data_format = "grok"
  grok_patterns = ['banIP/%{DATA:direction:tag}/%{WORD:verdict:tag}%{DATA}: %{GREEDYDATA}LEN=%{NUMBER:packet_len:int}']

  [inputs.tail.tags]
    influxdb_db = "os-metrics"
