# banIP monitoring

# blocked packets (nftables drop/reject)
[[inputs.tail]]
  name_override = "banip"
  files = ["/var/log/messages"]
  from_beginning = false
  data_format = "grok"
  grok_patterns = ['banIP/%{DATA:chain:tag}/%{WORD:verdict:tag}/%{DATA:feed:tag}: %{GREEDYDATA}SRC=%{IP:src:tag}%{GREEDYDATA}DST=%{IP:dst:tag}%{GREEDYDATA}LEN=%{NUMBER:blocked_bytes:int}']

  [inputs.tail.tags]
    influxdb_db = "os-metrics"

# dynamically banned IPs (fail2ban-like "add IP")
[[inputs.tail]]
  name_override = "banip"
  files = ["/var/log/messages"]
  from_beginning = false
  data_format = "grok"
  grok_patterns = ["banIP%{DATA}\\[%{NUMBER:banned:int}\\]: add IP '%{IP:ip:tag}'"]

  [inputs.tail.tags]
    influxdb_db = "os-metrics"
