# Parse netifyd metrics from HTTP sink
# The netifyd service sends metrics via HTTP POST to this endpoint
# See packages/telegraf/files/netifyd/netify-sink-http-telegraf.json for sink configuration
[[inputs.http_listener_v2]]
  ## Address and port to listen on
  service_address = "127.0.0.1:8087"

  ## Paths this server serves
  paths = ["/netifyd"]

  ## Use TLS for https, enter the certfile and keyfile path
  # tls_cert = ""
  # tls_key = ""

  ## HTTP methods to accept
  methods = ["POST"]

  ## Response code
  http_success_code = 200

  ## Data format to consume.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
  data_format = "json_v2"

  ## Global tags to add to all metrics from this input
  [inputs.http_listener_v2.tags]
    influxdb_db = "netifyd"

  [[inputs.http_listener_v2.json_v2]]
    measurement_name = "netifyd"
    timestamp_path = "log_time_end"
    timestamp_format = "unix"
    [[inputs.http_listener_v2.json_v2.object]]
      path = "stats"
      tags = ["detected_application_name", "detected_protocol_name", "interface", "internal", "ip_protocol", "ip_version", "local_ip", "local_mac", "local_origin", "other_ip", "other_port", "other_type"]
      excluded_keys = ["digests"]
