# Netify plugins config for Telegraf - Local and Sede
#
##############################################################################

[proc-aggregator-telegraf]
enable = yes
plugin_library = ${path_plugin_libdir}/libnetify-proc-aggregator.so.0.0.0
conf_filename = ${path_state_persistent}/netify-proc-aggregator-telegraf.json

[sink-http-telegraf]
enable = yes
plugin_library = ${path_plugin_libdir}/libnetify-sink-http.so.0.0.0
conf_filename = ${path_state_persistent}/netify-sink-http-telegraf.json

# vim: set ft=dosini :
