name: "python3-nethsec test image"

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/python3-nethsec-test-image.yml"
      - "packages/python3-nethsec/builder/**"
      - "packages/python3-nethsec/Containerfile"
      - "packages/python3-nethsec/requirements.txt"

permissions:
  packages: write

jobs:
  publish_images:
    name: "Build and publish"
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: packages/python3-nethsec
    env:
      IMAGETAG: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v7
      - id: build
        run: ./builder/build.sh
      - id: publish
        run: |
          # Publish the branch
          trap 'buildah logout ghcr.io' EXIT
          buildah login -u ${{ github.actor }} --password-stdin ghcr.io <<<"${{ secrets.GITHUB_TOKEN }}"
          images=(${{ steps.build.outputs.images }})
          urls=""
          for image in "${images[@]}" ; do
            buildah push $image docker://${image}:${IMAGETAG:?}
            if [[ "${IMAGETAG}" == "main" || "${IMAGETAG}" == "master" ]]; then
                buildah push $image docker://${image}:latest
            fi
            urls="${image}:${IMAGETAG} "$'\n'"${urls}"
          done
          echo "::notice title=Image URLs::${urls}"
